FROM golang:VERSION

RUN apt-get update && apt-get install apt-utils apt-transport-https -y && \
	echo 'deb https://apt.dockerproject.org/repo debian-stretch main' >> /etc/apt/sources.list && \
	apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys F76221572C52609D && \
	apt-get update && \
	apt-get install docker-compose docker-engine -y && \
	apt-get clean

ADD docker-entrypoint.sh .

VOLUME ["/var/run/docker.sock"]

ENTRYPOINT ["./docker-entrypoint.sh"]
